#!/bin/bash

set -eux

RLY_BINARY=../../build/uly
RLY="${RLY_BINARY} --debug"

CHAINID_ONE=ibc4
CHAINID_TWO=ibc5
PATH_NAME=ibc45

$RLY paths add $CHAINID_ONE $CHAINID_TWO $PATH_NAME --file=./configs/path.json

$RLY tx clients $PATH_NAME
$RLY tx connection $PATH_NAME
$RLY tx channel $PATH_NAME
