#!/bin/bash

set -e

SCRIPT_DIR=$(cd $(dirname $0); pwd)
RLY_BINARY=${SCRIPT_DIR}/../../../../build/uly
RLY="${RLY_BINARY} --debug"

CORDA_CLI='docker run --rm --userns host --network host yui-corda-ibc-client yui-corda-ibc-client'

# Ensure ${CHAIN_BINARY} is installed
if ! [ -x ${CHAIN_BINARY} ]; then
  echo "Error: ${CHAIN_BINARY} is not installed." >&2
  exit 1
fi

# XXX set proper value
TX_INTERNAL=3

CORDA_ADDRESS=$(${CORDA_CLI} node address-from-name -e http://localhost:9999 -n PartyA)
FABRIC_ADDRESS=$(${RLY} fabric wallet address ibc1 | tail -n 1)

DENOM=USD$(${CORDA_CLI} node pubkey-from-name -e http://localhost:9999 -n Notary)

echo "!!! Corda -> Fabric !!!"

echo "Before Cor balance: $(${RLY} query balance ibc0 ${CORDA_ADDRESS})"
echo "Before Fab balance: $(${RLY} query balance ibc1 ${FABRIC_ADDRESS} | tail -n 1)"
${RLY} tx transfer ibc01 ibc0 ibc1 100${DENOM} ${FABRIC_ADDRESS}
sleep ${TX_INTERNAL}
${RLY} tx relay ibc01
sleep ${TX_INTERNAL}
${RLY} tx acks ibc01
sleep ${TX_INTERNAL}
echo "After Cor balance: $(${RLY} query balance ibc0 ${CORDA_ADDRESS})"
echo "After Fab balance: $(${RLY} query balance ibc1 ${FABRIC_ADDRESS} | tail -n 1)"

echo "!!! Fabric -> Corda !!!"

echo "Before Cor balance: $(${RLY} query balance ibc0 ${CORDA_ADDRESS})"
echo "Before Fab balance: $(${RLY} query balance ibc1 ${FABRIC_ADDRESS} | tail -n 1)"
${RLY} tx transfer ibc01 ibc1 ibc0 100transfer/channel-0/${DENOM} ${CORDA_ADDRESS}
sleep ${TX_INTERNAL}
${RLY} tx relay ibc01
sleep ${TX_INTERNAL}
${RLY} tx acks ibc01
sleep ${TX_INTERNAL}
echo "After Cor balance: $(${RLY} query balance ibc0 ${CORDA_ADDRESS})"
echo "After Fab balance: $(${RLY} query balance ibc1 ${FABRIC_ADDRESS} | tail -n 1)"
