#!/bin/bash

set -x

# two-chainz creates two ${CHAIN_BINARY} chains and configures the relayer to 

RLY_BINARY=../../build/uly
RLY="${RLY_BINARY} --debug"
FIXTURES_DIR=./fixtures

# Ensure ${RLY_BINARY} is installed
if ! [ -x ${RLY_BINARY} ]; then
  echo "Error: ${RLY_BINARY} is not installed." >&2
  exit 1
fi

# Assume corda chain is already started
#./scripts/corda-chain

# Run fabric chain
./scripts/fab-chain

echo "Generating ${RLY_BINARY} configurations..."

${RLY} config init
${RLY} chains add-dir configs/demo/

# setup wallet for fabric client
${RLY} fabric wallet populate ibc5 --cert ${FIXTURES_DIR}/certs/org1-user-signcert.pem --key ${FIXTURES_DIR}/keys/clients/org1-user-priv_sk
# initialize the state of chaincode
${RLY} fabric chaincode init ibc5
