#!/bin/bash

set -e

RLY_BINARY=../../build/uly
RLY="${RLY_BINARY} --debug"

${RLY} tx transfer ibc23 ibc2 ibc3 10USD cosmos1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqnrql8a --timeout-time-offset 100s
${RLY} tx relay ibc23
${RLY} tx acks ibc23

${RLY} tx transfer ibc23 ibc3 ibc2 10transfer/ibcthreexfer/USD cosmos1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqnrql8a --timeout-time-offset 100s
${RLY} tx relay ibc23
${RLY} tx acks ibc23
