#!/bin/bash

set -eux

SCRIPT_DIR=$(cd $(dirname $0); pwd)
RLY_BINARY=${SCRIPT_DIR}/../../../../build/yrly
RLY="${RLY_BINARY} --debug"
CONFIG=$HOME/.yui-relayer/config/config.json

cat $CONFIG|jq
OLD_SRC_CLIENT_ID=$(cat $CONFIG | jq -r '.paths.ibc01.src["client-id"]')
OLD_DST_CLIENT_ID=$(cat $CONFIG | jq -r '.paths.ibc01.dst["client-id"]')

cp $CONFIG $CONFIG.tmp

cat $CONFIG.tmp \
    | jq '.paths.ibc01.dst["client-id"] |= ""' \
    > $CONFIG
$RLY tx clients --src-height 2 ibc01
NEW_SRC_CLIENT_ID=$(cat $CONFIG | jq -r '.paths.ibc01.src["client-id"]')
NEW_DST_CLIENT_ID=$(cat $CONFIG | jq -r '.paths.ibc01.dst["client-id"]')

if [ "$NEW_SRC_CLIENT_ID" != "$OLD_SRC_CLIENT_ID" ]; then
  echo "src client id is changed."
  exit 1
fi
if [ "$NEW_DST_CLIENT_ID" = "$OLD_DST_CLIENT_ID" ]; then
  echo "dst client id is not renewed."
  exit 1
fi
if [ "$NEW_DST_CLIENT_ID" = "" ]; then
  echo "new dst client id is empty."
  exit 1
fi

cat $CONFIG.tmp \
    | jq '.paths.ibc01.src["client-id"] |= ""' \
    > $CONFIG
$RLY tx clients --src-height 2 ibc01
NEW_SRC_CLIENT_ID=$(cat $CONFIG | jq -r '.paths.ibc01.src["client-id"]')
NEW_DST_CLIENT_ID=$(cat $CONFIG | jq -r '.paths.ibc01.dst["client-id"]')

if [ "$NEW_SRC_CLIENT_ID" = "$OLD_SRC_CLIENT_ID" ]; then
  echo "src client id is not renewed."
  exit 1
fi
if [ "$NEW_SRC_CLIENT_ID" = "" ]; then
  echo "new src client id is empty."
  exit 1
fi
if [ "$NEW_DST_CLIENT_ID" != "$OLD_DST_CLIENT_ID" ]; then
  echo "dst client id is changed."
  exit 1
fi

mv $CONFIG.tmp $CONFIG
