#!/bin/bash

set -eux

SCRIPT_DIR=$(cd $(dirname $0); pwd)
RLY_BINARY=${SCRIPT_DIR}/../../../../build/yrly
RLY="${RLY_BINARY} --debug"

source ${SCRIPT_DIR}/../../../scripts/set-telemetry-envvars
source ${SCRIPT_DIR}/utils

# XXX set proper value
TX_INTERNAL=3

TM_ADDRESS0=$(${RLY} tendermint keys show ibc0 testkey)
TM_ADDRESS1=$(${RLY} tendermint keys show ibc1 testkey)

echo "!!! ibc1 <-> ibc0 !!!"
export DEBUG_RELAYER_PRUNE_AFTER_BLOCKS_CHAIN_ibc0="10"
export DEBUG_RELAYER_PRUNE_AFTER_BLOCKS_PROVER_ibc0="10"
export DEBUG_RELAYER_SHFU_WAIT_ibc1="20"

expectUnrelayedCount "unrelayed-packets" "src" 0
expectUnrelayedCount "unrelayed-packets" "dst" 0
expectUnrelayedCount "unrelayed-acknowledgements" "src" 0
expectUnrelayedCount "unrelayed-acknowledgements" "dst" 0

docker exec tendermint-chain0 sh -c "simd --home /root/data/ibc0 tx --keyring-backend=test --from ${TM_ADDRESS0} --chain-id ibc0 mockapp send mockapp channel-0 'mock packet data' --yes"
docker exec tendermint-chain1 sh -c "simd --home /root/data/ibc1 tx --keyring-backend=test --from ${TM_ADDRESS1} --chain-id ibc1 mockapp send mockapp channel-0 'mock packet data' --yes"
sleep ${TX_INTERNAL}

expectUnrelayedCount "unrelayed-packets" "src" 1
expectUnrelayedCount "unrelayed-packets" "dst" 1
expectUnrelayedCount "unrelayed-acknowledgements" "src" 0
expectUnrelayedCount "unrelayed-acknowledgements" "dst" 0

${RLY} tx relay --do-refresh ibc01 --src-seqs 1 --dst-seqs 1
sleep ${TX_INTERNAL}
expectUnrelayedCount "unrelayed-packets" "src" 0
expectUnrelayedCount "unrelayed-packets" "dst" 0
expectUnrelayedCount "unrelayed-acknowledgements" "src" 1
expectUnrelayedCount "unrelayed-acknowledgements" "dst" 1

${RLY} tx acks --do-refresh ibc01 --src-seqs 1 --dst-seqs 1
sleep ${TX_INTERNAL}
expectUnrelayedCount "unrelayed-packets" "src" 0
expectUnrelayedCount "unrelayed-packets" "dst" 0
expectUnrelayedCount "unrelayed-acknowledgements" "src" 0
expectUnrelayedCount "unrelayed-acknowledgements" "dst" 0

