#!/bin/bash

set -eux

SCRIPT_DIR=$(cd $(dirname $0); pwd)
RLY_BINARY=${SCRIPT_DIR}/../../../../build/yrly
RLY="${RLY_BINARY} --debug"

# XXX set proper value
TX_INTERNAL=3

TM_ADDRESS0=$(${RLY} tendermint keys show ibc0 testkey)
TM_ADDRESS1=$(${RLY} tendermint keys show ibc1 testkey)

echo "!!! ibc0 -> ibc1 !!!"

docker exec tendermint-chain0 sh -c "simd --home /root/data/ibc0 tx --keyring-backend=test --from ${TM_ADDRESS0} --chain-id ibc0 mockapp send mockapp channel-0 'mock packet data' --yes"
sleep ${TX_INTERNAL}
${RLY} tx relay --do-refresh ibc01 --src-seqs 1
sleep ${TX_INTERNAL}
${RLY} tx acks --do-refresh ibc01 --dst-seqs 1

echo "!!! ibc1 -> ibc0 !!!"

docker exec tendermint-chain1 sh -c "simd --home /root/data/ibc1 tx --keyring-backend=test --from ${TM_ADDRESS1} --chain-id ibc1 mockapp send mockapp channel-0 'mock packet data' --yes"
sleep ${TX_INTERNAL}
${RLY} tx relay --do-refresh ibc01 --dst-seqs 1
sleep ${TX_INTERNAL}
${RLY} tx acks --do-refresh ibc01 --src-seqs 1
