#!/usr/bin/env bash

expectUnrelayedCount() {
    query_type=$1
    filter=".$2 | length"
    expect_count=$3
    unrelayed_count=$(${RLY} query ${query_type} ibc01 | jq "${filter}")
    if [ $unrelayed_count -ne ${expect_count} ]; then
        echo "$query_type: $unrelayed_count"
        kill $RLY_PID
        exit 1
    fi
}
