// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/api/api.proto

package server

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/x/ibc/core/04-channel/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryPacketRequest struct {
	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Chain    string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *QueryPacketRequest) Reset()         { *m = QueryPacketRequest{} }
func (m *QueryPacketRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPacketRequest) ProtoMessage()    {}
func (*QueryPacketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81cbfe6b72385977, []int{0}
}
func (m *QueryPacketRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPacketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPacketRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPacketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPacketRequest.Merge(m, src)
}
func (m *QueryPacketRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPacketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPacketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPacketRequest proto.InternalMessageInfo

type QueryPacketResponse struct {
	Packet *types.Packet `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
}

func (m *QueryPacketResponse) Reset()         { *m = QueryPacketResponse{} }
func (m *QueryPacketResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPacketResponse) ProtoMessage()    {}
func (*QueryPacketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81cbfe6b72385977, []int{1}
}
func (m *QueryPacketResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPacketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPacketResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPacketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPacketResponse.Merge(m, src)
}
func (m *QueryPacketResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPacketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPacketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPacketResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryPacketRequest)(nil), "relayer.api.QueryPacketRequest")
	proto.RegisterType((*QueryPacketResponse)(nil), "relayer.api.QueryPacketResponse")
}

func init() { proto.RegisterFile("relayer/api/api.proto", fileDescriptor_81cbfe6b72385977) }

var fileDescriptor_81cbfe6b72385977 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x8d, 0xfb, 0xda, 0xea, 0x3d, 0x77, 0xf3, 0x2b, 0x52, 0x09, 0x28, 0x94, 0x0e, 0xa8, 0x03,
	0xf2, 0x55, 0x5b, 0xbe, 0x00, 0x31, 0x31, 0x41, 0xc7, 0x6e, 0x8e, 0x31, 0x49, 0x44, 0xb0, 0x83,
	0xe3, 0x54, 0xaa, 0xaa, 0x2e, 0x0c, 0xcc, 0x95, 0xf8, 0xa9, 0x8e, 0x95, 0x58, 0x18, 0xa1, 0xe5,
	0x43, 0x50, 0x9c, 0x04, 0x15, 0x21, 0x86, 0x24, 0xf7, 0x9e, 0x7b, 0xee, 0xd1, 0x39, 0xb1, 0xf1,
	0x9e, 0x16, 0x31, 0x9b, 0x09, 0x0d, 0x2c, 0x89, 0xf2, 0x87, 0x26, 0x5a, 0x19, 0x45, 0x5a, 0x25,
	0x4c, 0x59, 0x12, 0xb9, 0xed, 0x40, 0x05, 0xca, 0xe2, 0x90, 0x57, 0x05, 0xc5, 0xdd, 0x0f, 0x94,
	0x0a, 0x62, 0x01, 0xb6, 0xf3, 0xb3, 0x5b, 0x60, 0x72, 0x56, 0x8e, 0x0e, 0xcb, 0x91, 0xd5, 0x94,
	0x52, 0x19, 0x66, 0x22, 0x25, 0xd3, 0x72, 0x7a, 0x1c, 0xf9, 0x1c, 0xb8, 0xd2, 0x02, 0x78, 0xc8,
	0xa4, 0x14, 0x31, 0x4c, 0x07, 0x55, 0x59, 0x50, 0x7a, 0x13, 0x4c, 0xae, 0x33, 0xa1, 0x67, 0x57,
	0x8c, 0xdf, 0x09, 0x33, 0x16, 0x0f, 0x99, 0x48, 0x0d, 0x21, 0xb8, 0x9e, 0x30, 0x13, 0x76, 0x50,
	0x17, 0xf5, 0xff, 0x8d, 0x6d, 0x4d, 0xda, 0xb8, 0xc1, 0x43, 0x16, 0xc9, 0x4e, 0xcd, 0x82, 0x45,
	0x43, 0x5c, 0xfc, 0x37, 0xcd, 0x97, 0x24, 0x17, 0x9d, 0x3f, 0x5d, 0xd4, 0xaf, 0x8f, 0xbf, 0xfa,
	0xde, 0x25, 0xfe, 0xff, 0x4d, 0x3b, 0x4d, 0x94, 0x4c, 0x05, 0x19, 0xe1, 0x66, 0x62, 0x11, 0x2b,
	0xdf, 0x1a, 0x1e, 0xd0, 0xc8, 0xe7, 0x34, 0xb7, 0x49, 0x2b, 0x6f, 0xd3, 0x01, 0x2d, 0x97, 0x4a,
	0xea, 0x70, 0x89, 0x70, 0xc3, 0x8a, 0x91, 0x27, 0x84, 0x5b, 0x3b, 0xb2, 0xe4, 0x88, 0xee, 0xfc,
	0x41, 0xfa, 0x33, 0x8c, 0xdb, 0xfd, 0x9d, 0x50, 0x38, 0xea, 0x9d, 0x3d, 0xbe, 0x7c, 0x3c, 0xd7,
	0x28, 0x39, 0x85, 0x3c, 0x29, 0xcc, 0xf3, 0xf7, 0x02, 0x6c, 0x40, 0x98, 0xdb, 0xcf, 0x02, 0x0a,
	0x1f, 0x30, 0xaf, 0xd2, 0x2d, 0xce, 0x2f, 0x56, 0xef, 0x9e, 0xb3, 0xda, 0x78, 0x68, 0xbd, 0xf1,
	0xd0, 0xdb, 0xc6, 0x43, 0xcb, 0xad, 0xe7, 0xac, 0xb7, 0x9e, 0xf3, 0xba, 0xf5, 0x9c, 0xc9, 0x49,
	0x10, 0x99, 0x30, 0xf3, 0x29, 0x57, 0xf7, 0x70, 0xc3, 0x0c, 0xb3, 0x32, 0x31, 0xf3, 0xa1, 0xba,
	0x06, 0xa9, 0xd0, 0x53, 0xa1, 0xfd, 0xa6, 0x3d, 0x87, 0xd1, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa6, 0x63, 0x24, 0x7c, 0x1f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	QueryPacket(ctx context.Context, in *QueryPacketRequest, opts ...grpc.CallOption) (*QueryPacketResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryPacket(ctx context.Context, in *QueryPacketRequest, opts ...grpc.CallOption) (*QueryPacketResponse, error) {
	out := new(QueryPacketResponse)
	err := c.cc.Invoke(ctx, "/relayer.api.Query/QueryPacket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	QueryPacket(context.Context, *QueryPacketRequest) (*QueryPacketResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryPacket(ctx context.Context, req *QueryPacketRequest) (*QueryPacketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPacket not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPacketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relayer.api.Query/QueryPacket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryPacket(ctx, req.(*QueryPacketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "relayer.api.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryPacket",
			Handler:    _Query_QueryPacket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relayer/api/api.proto",
}

func (m *QueryPacketRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPacketRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPacketRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sequence != 0 {
		i = encodeVarintApi(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintApi(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintApi(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPacketResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPacketResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPacketResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Packet != nil {
		{
			size, err := m.Packet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintApi(dAtA []byte, offset int, v uint64) int {
	offset -= sovApi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryPacketRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	if m.Sequence != 0 {
		n += 1 + sovApi(uint64(m.Sequence))
	}
	return n
}

func (m *QueryPacketResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Packet != nil {
		l = m.Packet.Size()
		n += 1 + l + sovApi(uint64(l))
	}
	return n
}

func sovApi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApi(x uint64) (n int) {
	return sovApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryPacketRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPacketRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPacketRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPacketResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPacketResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPacketResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Packet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Packet == nil {
				m.Packet = &types.Packet{}
			}
			if err := m.Packet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApi = fmt.Errorf("proto: unexpected end of group")
)
