#!/bin/bash

set -eux

SCRIPT_DIR=$(cd $(dirname $0); pwd)
RLY_BINARY=${SCRIPT_DIR}/../../../../build/yrly
RLY="${RLY_BINARY} --debug"

source ${SCRIPT_DIR}/utils

TM_ADDRESS0=$(${RLY} tendermint keys show ibc0 testkey)
TM_ADDRESS1=$(${RLY} tendermint keys show ibc1 testkey)

RETRY_COUNT=5
RETRY_INTERVAL=1

echo "!!! ibc0 -> ibc1 !!!"

echo "Before ibc0 balance: $(${RLY} query balance ibc0 ${TM_ADDRESS0})"
echo "Before ibc1 balance: $(${RLY} query balance ibc1 ${TM_ADDRESS1})"

# transfer a token (sendPacket)
${RLY} tx transfer ibc01 ibc0 ibc1 100samoleans ${TM_ADDRESS1}

waitRelay "unrelayed-packets" "src"

# relay the packet (recvPacket)
${RLY} tx relay --do-refresh ibc01

waitRelay "unrelayed-acknowledgements" "dst"

# relay the ack for the packet (acknowledgePacket)
${RLY} tx acks --do-refresh ibc01

waitRelay "unrelayed-acknowledgements" "dst"

echo "After ibc0 balance: $(${RLY} query balance ibc0 ${TM_ADDRESS0})"
echo "After ibc1 balance: $(${RLY} query balance ibc1 ${TM_ADDRESS1})"
