#!/usr/bin/env bash
set -eu

DOCKER=docker
FIXTURES_DIR=./fixtures

## Setup test fixtures

set +x
rm -rf ${FIXTURES_DIR}
mkdir -p ${FIXTURES_DIR}/fabric/wallet
mkdir -p ${FIXTURES_DIR}/fabric/output
mkdir -p ${FIXTURES_DIR}/fabric/org1/peers
mkdir -p ${FIXTURES_DIR}/fabric/org1/users
mkdir -p ${FIXTURES_DIR}/fabric/org1/connection-profile

mkdir -p ${FIXTURES_DIR}/fabric/org2/peers
mkdir -p ${FIXTURES_DIR}/fabric/org2/users
mkdir -p ${FIXTURES_DIR}/fabric/org2/connection-profile
set -x


## copy fabric's sign cert and priv key from data container
ORG1MSP_CONFIG_PATH=organizations/peerOrganizations/org1.example.com
ORG1MSP_PEER0_CONFIG_PATH=peers/peer0.org1.example.com
ORG1MSP_USER1_CONFIG_PATH=users/User1@org1.example.com

${DOCKER} cp fabric-data.example.com:/data/${ORG1MSP_CONFIG_PATH}/${ORG1MSP_PEER0_CONFIG_PATH} ${FIXTURES_DIR}/fabric/org1/${ORG1MSP_PEER0_CONFIG_PATH}
${DOCKER} cp fabric-data.example.com:/data/${ORG1MSP_CONFIG_PATH}/${ORG1MSP_USER1_CONFIG_PATH} ${FIXTURES_DIR}/fabric/org1/${ORG1MSP_USER1_CONFIG_PATH}
${DOCKER} cp fabric-data.example.com:/data/connection-profile/org1/local.yaml ${FIXTURES_DIR}/fabric/org1/connection-profile/local.yaml

ORG2MSP_CONFIG_PATH=organizations/peerOrganizations/org2.example.com
ORG2MSP_PEER0_CONFIG_PATH=peers/peer0.org2.example.com
ORG2MSP_USER1_CONFIG_PATH=users/User1@org2.example.com

${DOCKER} cp fabric-data.example.com:/data/${ORG2MSP_CONFIG_PATH}/${ORG2MSP_PEER0_CONFIG_PATH} ${FIXTURES_DIR}/fabric/org2/${ORG2MSP_PEER0_CONFIG_PATH}
${DOCKER} cp fabric-data.example.com:/data/${ORG2MSP_CONFIG_PATH}/${ORG2MSP_USER1_CONFIG_PATH} ${FIXTURES_DIR}/fabric/org2/${ORG2MSP_USER1_CONFIG_PATH}
${DOCKER} cp fabric-data.example.com:/data/connection-profile/org2/local.yaml ${FIXTURES_DIR}/fabric/org2/connection-profile/local.yaml
