#!/bin/bash

set -e

RLY_BINARY=../../build/uly
RLY="${RLY_BINARY} --debug"

CORDA_ADDRESS=cosmos1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqnrql8a
FABRIC_ADDRESS=$(${RLY} fabric wallet address ibc5 | tail -n 1)

echo
echo '==================== BEGIN: TRANSFER1 ====================' 
echo
${RLY} tx transfer ibc45 ibc4 ibc5 10USD $FABRIC_ADDRESS --timeout-time-offset 100s
echo
echo '==================== END: TRANSFER1 ====================' 
echo

echo
echo '==================== BEGIN: RELAY1 ====================' 
echo
${RLY} tx relay ibc45
echo
echo '==================== END: RELAY1 ====================' 
echo


echo
echo '==================== BEGIN: ACKS1 ====================' 
echo
${RLY} tx acks ibc45
echo
echo '==================== END: ACKS1 ====================' 
echo

${RLY} query balance ibc5 $FABRIC_ADDRESS

echo
echo '==================== BEGIN: TRANSFER2 ====================' 
echo
${RLY} tx transfer ibc45 ibc4 ibc5 10USD $FABRIC_ADDRESS --timeout-time-offset 100s
echo
echo '==================== END: TRANSFER2 ====================' 
echo

echo
echo '==================== BEGIN: RELAY2 ====================' 
echo
${RLY} tx relay ibc45
echo
echo '==================== END: RELAY2 ====================' 
echo

echo
echo '==================== BEGIN: ACKS2 ====================' 
echo
${RLY} tx acks ibc45
echo
echo '==================== END: ACKS2 ====================' 
echo

${RLY} query balance ibc5 $FABRIC_ADDRESS

echo
echo '==================== BEGIN: TRANSFER3 ====================' 
echo
${RLY} tx transfer ibc45 ibc4 ibc5 10USD $FABRIC_ADDRESS --timeout-time-offset 100s
echo
echo '==================== END: TRANSFER3 ====================' 
echo

echo
echo '==================== BEGIN: RELAY3  ====================' 
echo
${RLY} tx relay ibc45
echo
echo '==================== END: RELAY3  ====================' 
echo

echo
echo '==================== BEGIN: ACKS3  ====================' 
echo
${RLY} tx acks ibc45
echo
echo '==================== END: ACKS3  ====================' 
echo

${RLY} query balance ibc5 $FABRIC_ADDRESS

echo
echo '==================== BEGIN: TRANSFER4 ====================' 
echo
${RLY} tx transfer ibc45 ibc5 ibc4 30transfer/ibcfivexfer/USD $CORDA_ADDRESS --timeout-time-offset 100s
echo
echo '==================== END: TRANSFER4 ====================' 
echo

echo
echo '==================== BEGIN: RELAY4  ====================' 
echo
${RLY} tx relay ibc45
echo
echo '==================== END: RELAY4  ====================' 
echo

echo
echo '==================== BEGIN: ACKS4  ====================' 
echo
${RLY} tx acks ibc45
echo
echo '==================== END: ACKS4  ====================' 
echo
