#!/usr/bin/env bash

source $(cd $(dirname "$0"); pwd)/util

ATTEMPT=$1
CONTAINER=$2

attempt_num=1

until [[ $(docker inspect --format='{{.State.Health.Status}}' $CONTAINER) == 'healthy' ]]
do
    let attempt_num++
    if (( attempt_num == ATTEMPT )); then
        echo "Attempt $attempt_num failed and there are no more attempts left!"
        exit 1
    else
        echo "Attempt $attempt_num failed! Trying again in 1 seconds..."
        sleep 1
    fi
done
